//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from llang.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IllangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class llangBaseListener : IllangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] llangParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] llangParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.toplevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterToplevel([NotNull] llangParser.ToplevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.toplevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitToplevel([NotNull] llangParser.ToplevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.export"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExport([NotNull] llangParser.ExportContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.export"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExport([NotNull] llangParser.ExportContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.libimport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLibimport([NotNull] llangParser.LibimportContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.libimport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLibimport([NotNull] llangParser.LibimportContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.globalVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalVar([NotNull] llangParser.GlobalVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.globalVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalVar([NotNull] llangParser.GlobalVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.fundef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFundef([NotNull] llangParser.FundefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.fundef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFundef([NotNull] llangParser.FundefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.structdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructdef([NotNull] llangParser.StructdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.structdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructdef([NotNull] llangParser.StructdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.enumdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumdef([NotNull] llangParser.EnumdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.enumdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumdef([NotNull] llangParser.EnumdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.defargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefargslist([NotNull] llangParser.DefargslistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.defargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefargslist([NotNull] llangParser.DefargslistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.defargitem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefargitem([NotNull] llangParser.DefargitemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.defargitem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefargitem([NotNull] llangParser.DefargitemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.structDeclList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclList([NotNull] llangParser.StructDeclListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.structDeclList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclList([NotNull] llangParser.StructDeclListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.structDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDecl([NotNull] llangParser.StructDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.structDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDecl([NotNull] llangParser.StructDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.enumDeclList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclList([NotNull] llangParser.EnumDeclListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.enumDeclList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclList([NotNull] llangParser.EnumDeclListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.enumDeclItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclItem([NotNull] llangParser.EnumDeclItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.enumDeclItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclItem([NotNull] llangParser.EnumDeclItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] llangParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] llangParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] llangParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] llangParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.flowstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlowstmt([NotNull] llangParser.FlowstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.flowstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlowstmt([NotNull] llangParser.FlowstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.whilestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhilestmt([NotNull] llangParser.WhilestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.whilestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhilestmt([NotNull] llangParser.WhilestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.forstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstmt([NotNull] llangParser.ForstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.forstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstmt([NotNull] llangParser.ForstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] llangParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] llangParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.retstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetstmt([NotNull] llangParser.RetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.retstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetstmt([NotNull] llangParser.RetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.varDeclStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclStmt([NotNull] llangParser.VarDeclStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.varDeclStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclStmt([NotNull] llangParser.VarDeclStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignStmt([NotNull] llangParser.AssignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignStmt([NotNull] llangParser.AssignStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.deferstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeferstmt([NotNull] llangParser.DeferstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.deferstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeferstmt([NotNull] llangParser.DeferstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.assignop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignop([NotNull] llangParser.AssignopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.assignop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignop([NotNull] llangParser.AssignopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.funcallStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncallStmt([NotNull] llangParser.FuncallStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.funcallStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncallStmt([NotNull] llangParser.FuncallStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.argslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgslist([NotNull] llangParser.ArgslistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.argslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgslist([NotNull] llangParser.ArgslistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] llangParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] llangParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarlist([NotNull] llangParser.VarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarlist([NotNull] llangParser.VarlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.elementlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementlist([NotNull] llangParser.ElementlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.elementlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementlist([NotNull] llangParser.ElementlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.unaryop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryop([NotNull] llangParser.UnaryopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.unaryop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryop([NotNull] llangParser.UnaryopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.multop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultop([NotNull] llangParser.MultopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.multop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultop([NotNull] llangParser.MultopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.addop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddop([NotNull] llangParser.AddopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.addop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddop([NotNull] llangParser.AddopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.shiftop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShiftop([NotNull] llangParser.ShiftopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.shiftop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShiftop([NotNull] llangParser.ShiftopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.compop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompop([NotNull] llangParser.CompopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.compop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompop([NotNull] llangParser.CompopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.eqop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqop([NotNull] llangParser.EqopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.eqop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqop([NotNull] llangParser.EqopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.bitwiseop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwiseop([NotNull] llangParser.BitwiseopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.bitwiseop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwiseop([NotNull] llangParser.BitwiseopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.logicop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicop([NotNull] llangParser.LogicopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.logicop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicop([NotNull] llangParser.LogicopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="llangParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypename([NotNull] llangParser.TypenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="llangParser.typename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypename([NotNull] llangParser.TypenameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
